# Training parameters
training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  device: 'cuda'  # will fall back to 'cpu' if cuda not available

# Tracking parameters
tracker:
  probe_layers: ['conv_layers.2']

# Activation Analysis Distance parameters
analysis:
  pca_n_components: 113
  k_neighbour: 13

# Model architecture
model:
  conv_channels: [32, 62, 62]
  kernel_size: 3
  num_classes: 10

# Visualization
visualization:
  num_samples: 10000
  fig_size: [15, 5]
  iterations: 500
  percentile: 95

# Data
data:
  data_dir: './data'
  train_normalize_mean: [0.1307]
  train_normalize_std: [0.3081]

# Image Generation Parameters
generation:
  image_size: 28
  font_size_ratio: 0.75  # Proportion of image size used for font
  target_ratio: 0.7  # Target character size relative to image size
  dot_size_ratio: 10  # Dot diameter is image_size divided by this value
  font_path: 'assets/fonts/NotoSansCJKjp-Regular.otf'
  # Number Mappings
  mappings:
    chinese: [ '零', '一', '二', '三', '四', '五', '六', '七', '八', '九' ]
    roman: [ 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX' ]
    dots: [ '1', '2', '3', '4', '5', '6', '7', '8', '9' ]
    misc: ['empty', 'filled']